### ISSUE TITLE
parser error 'yy.extend' is not a function

### ISSUE THREAD

**Issue by chauthai** [agershun/WebSQLShim#2]
I'm looking for SQL parsers for a small project and tried your Jison grammar.
However I've encountered an error while trying it out:

my `index.js`:

``` javascript
// index.js

var parser = require('./sqliteparser.js').parser;

function exec (input) {
    return parser.parse(input);
}

var sql = exec('SELECT * FROM Table_A LEFT JOIN Table_B ON A.Key = B.Key WHERE B.Key IS NULL');

console.log(sql);
```

I used `jison sqliteparser.jison`to generate the sqliteparser.js.
The same approach as in your src folder. I've also tried out your generated file and I still get the same error message:

``` javascript
Users/thai/Documents/CrossMIP/mip-json-sql-parser/sqliteparser.js:520
case 234: this.$ = $$[$0-2]; yy.extend(this.$,$$[$0-1]); yy.extend(this.$,$$[$0]);
                                ^

TypeError: yy.extend is not a function
    at Object.anonymous (/Users/thai/Documents/CrossMIP/mip-json-sql-parser/sqliteparser.js:520:33)
    at Object.parse (/Users/thai/Documents/CrossMIP/mip-json-sql-parser/sqliteparser.js:858:36)
    at exec (/Users/thai/Documents/CrossMIP/mip-json-sql-parser/index.js:6:16)
    at Object.<anonymous> (/Users/thai/Documents/CrossMIP/mip-json-sql-parser/index.js:9:11)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
```

**Comment by agershun** [comment]
You can borrow this function (yy.extend()) from file [05utility.js](https://github.com/agershun/WebSQLShim/blob/master/src/05utility.js). Try to look at the file [10parser.js](https://github.com/agershun/WebSQLShim/blob/master/src/10parser.js) - here I attach this extend() function to yy object, which is used by Jison generated parser.

**Comment by agershun** [comment]
Also, you can find some examples, how to use parser here:

https://github.com/agershun/WebSQLShim/tree/master/test/parser

**Comment by chauthai** [comment]
Ok, thanks alot! It worked.
